---
title: "PH245_assignment1"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#1.


```{r}
#Loading data
setwd("/Users/xiaoyingliu/desktop")
dat1=read.table('dat1.txt',header=F,quote='')
colnames(dat1)=c('word-different', 
                       'word-same', 
                       'arabic-different', 
                       'arabic-same')
head(dat1)

#EDA
summary(dat1)
nrow(dat1)
boxplot(dat1)
plot(dat1)

#comments from EDA
#Variable in the dataset correlates with each other.I will consider there are in total 4 treatments. 
#Comparing parity will be considered as level of factors. The response variable is reaction time. 
#Null hypothesis: the cogntive processing time of numbers does not depend on how they are presented. 
#u1=u2=u3=u4
#Test:repeated measures design
#Reasoning: The treatment is independent to each other and all 4 treatment are testing the median 
#of cognitive processing time of numbers. 
#Test Statistics:T^2 = n(CXbar)Transpose(CSCTranspose)^-1(CXbar)

```
```{r}
# Gathering relevant variable data for the test statistic
n = nrow(dat1)
xBar = apply(dat1, 2, mean)
s = cov(dat1)
c = rbind(c(-1, 1, 0, 0), 
          c(0, -1, 1, 0),
          c(0, 0, -1, 1)
         )

tsquaredRepeatedMeasures = function(n, xBar, s, c) {
    return( n *
            t( c %*% xBar ) %*%
            solve( c %*% s %*% t(c) ) %*%
            c %*% xBar
          )
}
# Calculating test statistic
observedTestStatistic1= tsquaredRepeatedMeasures(n, xBar, s, c)
print(observedTestStatistic1)

# P-value is tSquared / ( (p)(n-1)/(n-p) ) in the F distribution
# n=nrows, p=degrees of freedom=num variables - 1
observedPValue1 = 1 - pf(q=observedTestStatistic1/ (3*31/29), 
                        df1=3, 
                        df2=31
                       )
print(observedPValue1)


#Test Statistic Interpretation
#Since the significance level of 0.05, we will reject the null hypothesis that the cognitive processing 
#of numbers doesn't depend on numbers are presented. However, the cognitive processing of numbers 
#does depend on the way numbers are presented and their parity.

```

#2.

```{r}
#Loading data 
dat2= read.table(file='dat2.txt', header=FALSE, quote='')
colnames(dat2) = c('Fuel', 
                       'Repair', 
                       'Capital',
                       'EngineType'
                      ) #per mile
head(dat2)


# EDA
summary(dat2)
nrow(dat2)
boxplot(formula=Fuel+Repair+Capital ~ EngineType, data=dat2)
plot(dat2)


#Comments from EDA
#We are testing if the two types of trucks have statistically significantly 
#different mean costs from each other. 
#Null Hypothesis: u1=u2, u1 is the mean costs of a gasoline truck and u2 is the mean
#costs of a diesel truck. The two types of trucks have the same mean costs per mile 
#in regards to the three observed variables.
#Alternative Hypothesis: u1!=u2, where u1 is the mean costs of a gasoline truck 
#and u2 is the mean costs of a diesel truck. The two types of trucks do not have 
#the same mean costs per mile to in regards to the three observed variables.
#Test: Comparing Mean Vectors from Two Populations. 
#Reasoning: We are comparing means from two different populations. 
#Test Statistic: (xBar1-xBar2)Transpose * (S(1/n1 + 1/n2))^-1 * (xBar1-xBar2)

gasoline = dat2[dat2$EngineType == 'gasoline',]
diesel = dat2[dat2$EngineType == 'diesel',]

```

```{r}
# preparing variables for tetsing
n1 = nrow(gasoline)
n2 = nrow(diesel)

xBar1 = apply(gasoline[1:3], 2, mean)
xBar2 = apply(diesel[1:3], 2, mean)

s = cov(dat2[1:3])

tsquaredTwoPopMeans = function(n1, n2, xBar1, xBar2, s) {
    return( t(xBar1 - xBar2) %*%
            solve(s * (1/n1 + 1/n2)) %*%
            (xBar1 - xBar2)
          )
}

# Calculating test statistic
observedTestStatistic2 = tsquaredTwoPopMeans(n1, n2, xBar1, xBar2, s)
observedTestStatistic2

# P-value is tSquared / ( (n1 + n2 - 2)(p)/(n1+n2-p-1) ) in the F distribution
# n=nrows, p=degrees of freedom=num variables - 1
observedPValue2 = 1 - pf(q=observedTestStatistic2 / ((n1+n2-2)*2/(n1+n2-2-1)), 
                        df1=2, 
                        df2=n1+n2-1
                       )
observedPValue2


#Test Statistic Interpretation
#With a significance level of .05, we can reject the null hypothesis that 
#the two types of trucks (diesel or gasoline) have the same mean costs per mile 
#with respect to the three observed variables.

```


#3.

```{r}
# Loading data
dat3 = read.table(file='dat3.txt', header=FALSE, quote='')
colnames(dat3) = c('max_breadth', 
                       'base_height', 
                       'base_length', 
                       'nasal_height',
                       'time_period'
                      )
head(dat3)


# EDA

period1 = dat3[dat3$time_period == 1,]
period2 = dat3[dat3$time_period == 2,]
period3 = dat3[dat3$time_period == 3,]

boxplot(period1[1:4])
boxplot(period2[1:4])
boxplot(period3[1:4])


#Comments from EDA
#We are testing if humans from resident population over three time periods have varying skull 
#sizes which would provide evidence of the resident population interbreeding with immigrant populations.
#Null Hypothesis: u1=u2=u3, tha there has been no change in skull size over the 
#course of the time periods
#Alternative Hypothesis: At least one ui != uj for any i,j. 
#that there has been a change in skull size over the course of the time periods
#Test: One-way MANOVA
#One-way MANOVA is chosen since we have one factor of 3 levels. 
#And our variables are dependent to each other(max breadth, base height, base length, nasal height). 

```

```{r}
#Statistical Test
timePeriod = as.factor(dat3$time_period)

results = manova(
    cbind(max_breadth, base_height, base_length, nasal_height) ~ timePeriod,
    data=dat3
)

results

summary(results)
summary.aov(results)


#Test Result Interpretation
#With a significance level of .05, we can reject the null hypothesis 
#that no interbreeding occurred.
#From summary results, there was statistically significant variance in two of the 
#variables over time.Which is max_breadth and base_length. 
```




#4.
```{r}
# Loading data
dat4 = read.table(file='dat4.txt', header=FALSE, quote='')
colnames(dat4) = c('reflectance_green', 
                       'reflectance_near_infared',
                       'species',
                       'time_period',
                       'treeID'
                      )
head(dat4)

#EDA
SS = dat4[dat4$species == 'SS',]
JL = dat4[dat4$species == 'JL',]
LP = dat4[dat4$species == 'LP',]

#EDA of SS
boxplot(reflectance_green ~ time_period, data=SS)
boxplot(reflectance_near_infared ~ time_period, data=SS)
#EDA of Species JL
boxplot(reflectance_green ~ time_period, data=JL)
boxplot(reflectance_near_infared ~ time_period, data=JL)
#EDA of Species LP
boxplot(reflectance_green ~ time_period, data=LP)
boxplot(reflectance_near_infared ~ time_period, data=LP)

###############
#Comments from EDA
#We are testing whether there is a difference between our two dependent variables 
#based on our two factors, species and time period. We're also trying to understand 
#whether an interaction effect exists between our two independent variables. 
#Null Hypothesis: u1=u2=u3, There is no species effect, no time effect, and no interaction effect 
#on the green and near-infared reflectance.
#Alternative Hypothesis:There is at least one of: 1) a species effect, 2) a time effect, 
#or 3) an interaction effect on the reflectance of the seedlings.
#Test: Two-way MANOVA
#Reasoning: we have two factors (time period, species) with 3 levels each (1, 2, 3; SS, JL, LP)
#and that affects multiple dependent variables (green and near-infared reflectance). 

```

```{r}
#Statistical Test
timePeriod = as.factor(dat4$time_period)
species = as.factor(dat4$species)

results = manova(
    cbind(reflectance_green, reflectance_near_infared) ~ timePeriod*species,
    data=dat4
)

results
summary(results)
summary.aov(results)


#Test Result Interpretation
#With a significance level of .05, we reject the null hypothesis that there is no species, 
#time period, or interaction effect.
#Based on the summary.aov results, there was statistically significant variance 
#in both reflectances for time and species effect. However, 
#Only green reflectance have an interation effect(with a significant level ***), 
#near_infared reflectance does not have an statistical significant interation effect.
```
